print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello, line 10")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")