print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello, lets create a conflict")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
print("Hello NB")
print("Hello Babai")
